### ISSUE TITLE
Test Calling library

### ISSUE THREAD

**Issue by halonazhao** [741ProjectFFT/FFT#12]
Hi Dr. @smiths,
I am thinking about how to test my library can be loaded successfully in different compilers(different versions but same language or different language compilers). I was thinking doing it manually but apparently, this is not feasible. I searched the methods but I think they didn't say a general tool I can do it automatedly. So can you give my some clues about this test? Thanks~

**Comment by smiths** [comment]
If you do not have another way to do it, testing your work manually with different compilers is fine.  It is better than not doing it at all.  However, this can be automated using make.  Your different commands for compiling and testing can be different rules in the makefile.  You can include a rule that applies all of the other rules.

If you really want to get fancy, Continuous Integration (CI) is worth investigating.  CI would let you compile in completely different environments, even with different OSs.  This is done by combining CI and docker, where docker provides a light weight virtual machine that can run any script that you give it.

I would prefer automation, but if this isn't feasible, you can include manual testing in  your plan.  The most important thing to do is to document your plan, no matter what it is.  😄

**Comment by halonazhao** [comment]
Thanks. I will try to figure out using make first. CI seems not gonna happen to me so far lol.

**Comment by smiths** [comment]
Sounds good.  😄
