### ISSUE TITLE
Please add me as a member

### ISSUE THREAD

**Issue by smiths** [741ProjectFFT/FFT#15]
Your project does not show up on my list of projects, so I have to search for it separately every time.  Can you please add me as a member on the project.

**Comment by halonazhao** [comment]
I did add you as contributor. But since you can not see it , so I removed and added again. Please let me know whether that works. The link is: [https://github.com/741ProjectFFT/FFT/invitations](url). @smiths

**Comment by smiths** [comment]
I'm not sure why I didn't see it previously, but I see it now.  Thank you.
