### ISSUE TITLE
Test Plan - Output --> Input

### ISSUE THREAD

**Issue by icbicket** [741ProjectFFT/FFT#17]
You say you are planning to use the output from the FFT test as the input to the IFFT test. I think you are compounding error by using the output again. Since you are calculating error and using the error as a measure of the quality of your programmed FFT and IFFT, this would be important. 

Say, your FFT has some error associated with it, when you do an IFFT on that output, you are adding the error from the FFT and from the IFFT, which makes your program seem worse than it is. Maybe you can use a new dataset for the IFFT? 

I like that you are comparing to Matlab as well for your error calculation, though.

**Comment by halonazhao** [comment]
Yes, I think you are right. This implementation may cause more regression errors.
fixed.https://github.com/741ProjectFFT/FFT/blob/29613ba24cfd1f94bd522d8d9661535189b3e2c7/Doc/TestPlan/TestPlan.tex#L147
