### ISSUE TITLE
Control Module

### ISSUE THREAD

**Issue by halonazhao** [741ProjectFFT/FFT#22]
I think I do need a control module because no matter how simple my library is, at least I have input verification module and calculation module. If I don't have a control module, the program will not know what is the logic to compute. So I am a bit confused about that day you said I might do not need a control module. Can you explain a bit about this? And I can not imagine a program who do not need a control module. Can you give me a simple example? @smiths    Thanks!

**Comment by smiths** [comment]
@halonazhao, I believe your confusion comes from thinking of your project as a program.  You are building an FFT library.  Other programs will use your library.  Have a look at the other FFT libraries that you surveyed for your project.  Do they have a control module?  Libraries do not actually do anything on their own.  

In your design you can show the external program as a box at the top of your uses hierarchy.  You can show the use relation between your modules and the external driver program.

For testing you will write a driver program (or programs), but this code is not part of your library, but part of the verification of your library.

**Comment by halonazhao** [comment]
I understand what your are saying. I don't want to control all functions together. My thinking is that for example, I have a function called R2ComplexFFT(data) and external program right invoke this function. I think this function itself is a control module because it includes all input, calculation and output modules and make them computed one by one. Isn't it? @smiths

**Comment by smiths** [comment]
Okay, I understand your question better now.  Yes, having an external program only have to interact with one function from your library is ideal.  That top level module can then use your other modules.  Sounds like a good starting point.  However, I don't think I would call this module "control."  Maybe this module could have the name of your library, or "external interface" or similar.

**Comment by halonazhao** [comment]
Thanks~
