### ISSUE TITLE
Example Needed

### ISSUE THREAD

**Issue by halonazhao** [741ProjectFFT/FFT#4]
Hello Dr. @smiths,
I feel the program example you gave to us is more related to a real physical problem. I feel some parts in the SRS document is a little difficult to fit into my Library-like project very well.  So do you have some other samples you have can give me as references? Thank you.

**Comment by smiths** [comment]
Hello @halonazhao.  I have added a commonality analysis template to the cas 741 repo.  You can follow that for your family.  The CA template is based on the Smith 2006 paper, with some minor modifications.  I do not have any complete and good examples of a general purpose library.
