### ISSUE TITLE
Goal Statements

### ISSUE THREAD

**Issue by aoananp** [741ProjectFFT/FFT#5]
https://github.com/741ProjectFFT/FFT/blob/1c4e0a934a30cf1c75691e090e5af6f816dd5a27/Doc/SRS/CA.tex#L455

The Goal Statements seem very specific to which algorithm is being performed (variabilities) depending on the input.
These should be general / high level goals on what the program is trying to solve based on your Problem Statement.
i.e. Given a set of inputs, produce a set of outputs.

**Comment by halonazhao** [comment]
Thanks, fixed.
