### ISSUE TITLE
Potential System Contexts - User Definition

### ISSUE THREAD

**Issue by aoananp** [741ProjectFFT/FFT#6]
https://github.com/741ProjectFFT/FFT/blob/1c4e0a934a30cf1c75691e090e5af6f816dd5a27/Doc/SRS/CA.tex#L219

It should give the reader a clearer sense of who or in this case, what, uses the program.
In a library of FFT solvers, there is a driver/wrapper program that shall provide the interface between the actual user (person) and the program in the library.
Please describe the driver program instead.

**Comment by halonazhao** [comment]
Thanks, fixed.
