### ISSUE TITLE
Empty Calculation and Output Sections

### ISSUE THREAD

**Issue by aoananp** [741ProjectFFT/FFT#8]
https://github.com/741ProjectFFT/FFT/blob/1c4e0a934a30cf1c75691e090e5af6f816dd5a27/Doc/SRS/CA.tex#L781

There should be content in the Calculation and Output sections which describe the intended functionality of the program such as:
- Check inputs if they satisfy assumptions
- Parse inputs if they adhere to the function prototype
- Perform calculations
- Describe the expected output
- Where will the output be located?

**Comment by halonazhao** [comment]
Yes, you are right. I am going to add radix-2 and radix-3 two different algorithms to this part.

**Comment by smiths** [comment]
@halonazhao, great to hear that you are going to take the advice from @aoananp.  However, please do not close the issue until after you have made the changes.

**Comment by halonazhao** [comment]
fixed.  https://github.com/741ProjectFFT/FFT/blob/29613ba24cfd1f94bd522d8d9661535189b3e2c7/Doc/SRS/CA.tex#L543
