### ISSUE TITLE
Please describe the expected behaviour of the program in an exception

### ISSUE THREAD

**Issue by aoananp** [741ProjectFFT/FFT#9]
https://github.com/741ProjectFFT/FFT/blob/1c4e0a934a30cf1c75691e090e5af6f816dd5a27/Doc/SRS/CA.tex#L759

If an exception is caught such that any one of the assumptions listed is not satisfied, what is the expected behaviour of the program?
For example, if the driver program sends an input X[k] such that the length of X[k] sequence is NOT equal to the length of sequence x(n).

**Comment by halonazhao** [comment]
I think for some situations, the programs will pop an error message informing user the computing result is wrong, like you said, the numbers of input and output are different. And for other situations, like the number of input doesn't satisfy 2^n or 3^n, the program will fill the rest with 0 to make the input satisfying the assumption.

**Comment by smiths** [comment]
@aoananp has raised a good point.  The answer suggests that no changes were actually made to address the original comment.  It seems to me (without actually checking) that the SRS should be modified to reflect what will happen in these situations.  In particular, the SRS should talk about when 0s are padded.

**Comment by halonazhao** [comment]
fixed. https://github.com/741ProjectFFT/FFT/blob/29613ba24cfd1f94bd522d8d9661535189b3e2c7/Doc/SRS/CA.tex#L165
